version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    groups:
      hot-chocolate:
        patterns:
          - "HotChocolate*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"