using System;

namespace Fluss.Regen.Helpers;

public static class CodeWriterExtensions
{
    public static void WriteFileHeader(this CodeWriter writer)
    {
        if (writer is null)
        {
            throw new ArgumentNullException(nameof(writer));
        }

        writer.WriteComment("<auto-generated/>");
        writer.WriteLine();
        writer.WriteIndentedLine("#nullable enable");
        writer.WriteLine();
        writer.WriteIndentedLine("using System;");
        writer.WriteIndentedLine("using System.Runtime.CompilerServices;");
    }

    public static CodeWriter WriteComment(this CodeWriter writer, string comment)
    {
        writer.WriteIndent();
        writer.Write("// ");
        writer.WriteLine(comment);
        return writer;
    }
}
