//HintName: SelectorAttribute.g.cs
// <auto-generated/>

namespace Fluss.Regen
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class SelectorAttribute : System.Attribute
    {
    }
}