//HintName: Registration.g.cs
// <auto-generated/>

#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace Microsoft.Extensions.DependencyInjection {
    public static partial class RegenTestsESComponentsComponentsServiceCollectionExtensions {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESComponentsUpcasters(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            global::Fluss.ServiceCollectionExtensions.AddUpcaster<global::TestNamespace.TestUpcaster>(sc);
            return sc;
        }

        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESComponentsComponents(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            AddRegenTestsESComponentsUpcasters(sc);
            return sc;
        }
    }
}
