//HintName: Attributes.g.cs
// <auto-generated/>

namespace Fluss.Regen
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    public class SelectorAttribute : System.Attribute
    {
    }
}

namespace Fluss.Regen
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
    public class CrudAttribute : System.Attribute
    {
    }
}
