//HintName: Registration.g.cs
// <auto-generated/>

#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace Microsoft.Extensions.DependencyInjection {
    public static partial class RegenTestsESComponentsComponentsServiceCollectionExtensions {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESComponentsPolicies(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            global::Fluss.Authentication.ServiceCollectionExtensions.AddPolicy<global::TestNamespace.TestPolicy>(sc);
            return sc;
        }

        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESComponentsComponents(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            AddRegenTestsESComponentsPolicies(sc);
            return sc;
        }
    }
}
