//HintName: Registration.g.cs
// <auto-generated/>

#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace Microsoft.Extensions.DependencyInjection {
    public static partial class RegenTestsESComponentsServiceCollectionExtensions {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESValidators(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            global::Fluss.Validation.ValidationServiceCollectionExtension.AddAggregateValidator<global::TestNamespace.TestAggregateValidator>(sc);
            return sc;
        }

        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRegenTestsESComponents(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection sc) {
            AddRegenTestsESValidators(sc);
            return sc;
        }
    }
}
