name: Publish on NuGet

on:
  release:
    types: [created]

env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ Fluss, Fluss.HotChocolate, Fluss.PostgreSQL, Fluss.Regen, Fluss.Testing ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x
      - name: Strip v from tag to determine version
        run: echo "VERSION=${VERSION/v/}" >> $GITHUB_ENV
      - name: Package
        run: dotnet pack --configuration Release /p:Version=${VERSION}
        working-directory: src/${{ matrix.package }}
      - name: Publish
        run: dotnet nuget push bin/Release/${{ matrix.package }}.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        working-directory: src/${{ matrix.package }}

